name: Test, Build and Upload microsService

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]

    name: Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn -f pom.xml clean compile


  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [4.2]
    needs: compile
    name: Java 8 build, deliver artifact and container
    steps:
      - name: checkout user repo
        uses: actions/checkout@v1
        With:
          repository: vranckxrobin/users-service

      - name: Test and build user repo project
        run: mvn -f pom.xml clean install

      - uses: actions/checkout@v1

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Test and build project
        run: mvn -f pom.xml clean install

      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: Build jar file
          path: ./target/demo-0.0.1-SNAPSHOT.jar

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/member-edgeservice-server-ex:latest .

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/member-edgeservice-server-ex:latest